#!/bin/bash

git stash -q --keep-index

echo "Running git pre-commit hook"

./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache

RESULT=$?

git stash pop -q

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && exit 1
exit 0
